name: Canary Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      space:
        description: 'Select the Deployment Stage'
        required: true
        type: choice
        options:
          - 'DEV'
          - 'INT'
          - 'PROD'

      canary-deploy:
        description: 'Run as Canary Deployment?'
        required: true
        default: false
        type: boolean

      git-ref:
        description: 'Set the Git Tag, Branch (e.g. main) or Commit SHA'
        required: true
        default: 'main'
        type: string

jobs:
  deployment:
    name: Deployment Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git-ref }}

      - name: Deploy Artifact
        if: ${{ inputs.canary-deploy == false }}
        shell: sh
        run: echo "[WARN] Placeholder. Not implemented yet."

      - name: Deploy Artifact (Canary)
        if: ${{ inputs.canary-deploy == true }}
        shell: sh
        run: echo "[WARN] Placeholder. Not implemented yet."

  deployment-evaluation:
    name: Deployment Evaluation
    runs-on: ubuntu-latest
    if: ${{ inputs.canary-deploy == true }}
    needs: deployment
    environment:
      name: deployment-approval
    steps:
      - name: Evaluate Deployment
        run: echo "Evaluating Deployment."

  continue-deployment:
    name: Continue Deployment Job
    runs-on: ubuntu-latest
    needs: deployment-evaluation
    if: ${{ always() && inputs.canary-deploy == true && needs.bg-evaluation.result == 'success' }}
    steps:
      - name: Update Environment to new Version
        if: ${{ env.decision == 'proceed' }}
        run: echo "Accept environment."

  rollback-deployment:
    name: Rollback Deployment Job
    runs-on: ubuntu-latest
    needs: deployment-evaluation
    if: ${{ always() && inputs.canary-deploy == true && needs.bg-evaluation.result != 'success' }}
    steps:
      - name: Rollback Environment to old Version
        run: echo "Rollback environment."
